/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Communication.proto */

#ifndef PROTOBUF_C_Communication_2eproto__INCLUDED
#define PROTOBUF_C_Communication_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005002 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct Trashsimulator__Join Trashsimulator__Join;
typedef struct Trashsimulator__JoinResponse Trashsimulator__JoinResponse;
typedef struct Trashsimulator__MoveCommand Trashsimulator__MoveCommand;
typedef struct Trashsimulator__MoveResponse Trashsimulator__MoveResponse;


/* --- enums --- */


/* --- messages --- */

struct  Trashsimulator__Join
{
  ProtobufCMessage base;
  int32_t join_code;
};
#define TRASHSIMULATOR__JOIN__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trashsimulator__join__descriptor) \
    , 0 }


struct  Trashsimulator__JoinResponse
{
  ProtobufCMessage base;
  int32_t client_id;
};
#define TRASHSIMULATOR__JOIN_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trashsimulator__join_response__descriptor) \
    , 0 }


struct  Trashsimulator__MoveCommand
{
  ProtobufCMessage base;
  int32_t client_id;
  int32_t command;
};
#define TRASHSIMULATOR__MOVE_COMMAND__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trashsimulator__move_command__descriptor) \
    , 0, 0 }


struct  Trashsimulator__MoveResponse
{
  ProtobufCMessage base;
  int32_t client_id;
  char *status;
};
#define TRASHSIMULATOR__MOVE_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&trashsimulator__move_response__descriptor) \
    , 0, (char *)protobuf_c_empty_string }


/* Trashsimulator__Join methods */
void   trashsimulator__join__init
                     (Trashsimulator__Join         *message);
size_t trashsimulator__join__get_packed_size
                     (const Trashsimulator__Join   *message);
size_t trashsimulator__join__pack
                     (const Trashsimulator__Join   *message,
                      uint8_t             *out);
size_t trashsimulator__join__pack_to_buffer
                     (const Trashsimulator__Join   *message,
                      ProtobufCBuffer     *buffer);
Trashsimulator__Join *
       trashsimulator__join__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trashsimulator__join__free_unpacked
                     (Trashsimulator__Join *message,
                      ProtobufCAllocator *allocator);
/* Trashsimulator__JoinResponse methods */
void   trashsimulator__join_response__init
                     (Trashsimulator__JoinResponse         *message);
size_t trashsimulator__join_response__get_packed_size
                     (const Trashsimulator__JoinResponse   *message);
size_t trashsimulator__join_response__pack
                     (const Trashsimulator__JoinResponse   *message,
                      uint8_t             *out);
size_t trashsimulator__join_response__pack_to_buffer
                     (const Trashsimulator__JoinResponse   *message,
                      ProtobufCBuffer     *buffer);
Trashsimulator__JoinResponse *
       trashsimulator__join_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trashsimulator__join_response__free_unpacked
                     (Trashsimulator__JoinResponse *message,
                      ProtobufCAllocator *allocator);
/* Trashsimulator__MoveCommand methods */
void   trashsimulator__move_command__init
                     (Trashsimulator__MoveCommand         *message);
size_t trashsimulator__move_command__get_packed_size
                     (const Trashsimulator__MoveCommand   *message);
size_t trashsimulator__move_command__pack
                     (const Trashsimulator__MoveCommand   *message,
                      uint8_t             *out);
size_t trashsimulator__move_command__pack_to_buffer
                     (const Trashsimulator__MoveCommand   *message,
                      ProtobufCBuffer     *buffer);
Trashsimulator__MoveCommand *
       trashsimulator__move_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trashsimulator__move_command__free_unpacked
                     (Trashsimulator__MoveCommand *message,
                      ProtobufCAllocator *allocator);
/* Trashsimulator__MoveResponse methods */
void   trashsimulator__move_response__init
                     (Trashsimulator__MoveResponse         *message);
size_t trashsimulator__move_response__get_packed_size
                     (const Trashsimulator__MoveResponse   *message);
size_t trashsimulator__move_response__pack
                     (const Trashsimulator__MoveResponse   *message,
                      uint8_t             *out);
size_t trashsimulator__move_response__pack_to_buffer
                     (const Trashsimulator__MoveResponse   *message,
                      ProtobufCBuffer     *buffer);
Trashsimulator__MoveResponse *
       trashsimulator__move_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   trashsimulator__move_response__free_unpacked
                     (Trashsimulator__MoveResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Trashsimulator__Join_Closure)
                 (const Trashsimulator__Join *message,
                  void *closure_data);
typedef void (*Trashsimulator__JoinResponse_Closure)
                 (const Trashsimulator__JoinResponse *message,
                  void *closure_data);
typedef void (*Trashsimulator__MoveCommand_Closure)
                 (const Trashsimulator__MoveCommand *message,
                  void *closure_data);
typedef void (*Trashsimulator__MoveResponse_Closure)
                 (const Trashsimulator__MoveResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor trashsimulator__join__descriptor;
extern const ProtobufCMessageDescriptor trashsimulator__join_response__descriptor;
extern const ProtobufCMessageDescriptor trashsimulator__move_command__descriptor;
extern const ProtobufCMessageDescriptor trashsimulator__move_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_Communication_2eproto__INCLUDED */
