/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: Communication.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "Communication.pb-c.h"
void   trashsimulator__join__init
                     (Trashsimulator__Join         *message)
{
  static const Trashsimulator__Join init_value = TRASHSIMULATOR__JOIN__INIT;
  *message = init_value;
}
size_t trashsimulator__join__get_packed_size
                     (const Trashsimulator__Join *message)
{
  assert(message->base.descriptor == &trashsimulator__join__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trashsimulator__join__pack
                     (const Trashsimulator__Join *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trashsimulator__join__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trashsimulator__join__pack_to_buffer
                     (const Trashsimulator__Join *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trashsimulator__join__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Trashsimulator__Join *
       trashsimulator__join__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Trashsimulator__Join *)
     protobuf_c_message_unpack (&trashsimulator__join__descriptor,
                                allocator, len, data);
}
void   trashsimulator__join__free_unpacked
                     (Trashsimulator__Join *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trashsimulator__join__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trashsimulator__join_response__init
                     (Trashsimulator__JoinResponse         *message)
{
  static const Trashsimulator__JoinResponse init_value = TRASHSIMULATOR__JOIN_RESPONSE__INIT;
  *message = init_value;
}
size_t trashsimulator__join_response__get_packed_size
                     (const Trashsimulator__JoinResponse *message)
{
  assert(message->base.descriptor == &trashsimulator__join_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trashsimulator__join_response__pack
                     (const Trashsimulator__JoinResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trashsimulator__join_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trashsimulator__join_response__pack_to_buffer
                     (const Trashsimulator__JoinResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trashsimulator__join_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Trashsimulator__JoinResponse *
       trashsimulator__join_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Trashsimulator__JoinResponse *)
     protobuf_c_message_unpack (&trashsimulator__join_response__descriptor,
                                allocator, len, data);
}
void   trashsimulator__join_response__free_unpacked
                     (Trashsimulator__JoinResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trashsimulator__join_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trashsimulator__move_command__init
                     (Trashsimulator__MoveCommand         *message)
{
  static const Trashsimulator__MoveCommand init_value = TRASHSIMULATOR__MOVE_COMMAND__INIT;
  *message = init_value;
}
size_t trashsimulator__move_command__get_packed_size
                     (const Trashsimulator__MoveCommand *message)
{
  assert(message->base.descriptor == &trashsimulator__move_command__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trashsimulator__move_command__pack
                     (const Trashsimulator__MoveCommand *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trashsimulator__move_command__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trashsimulator__move_command__pack_to_buffer
                     (const Trashsimulator__MoveCommand *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trashsimulator__move_command__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Trashsimulator__MoveCommand *
       trashsimulator__move_command__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Trashsimulator__MoveCommand *)
     protobuf_c_message_unpack (&trashsimulator__move_command__descriptor,
                                allocator, len, data);
}
void   trashsimulator__move_command__free_unpacked
                     (Trashsimulator__MoveCommand *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trashsimulator__move_command__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   trashsimulator__move_response__init
                     (Trashsimulator__MoveResponse         *message)
{
  static const Trashsimulator__MoveResponse init_value = TRASHSIMULATOR__MOVE_RESPONSE__INIT;
  *message = init_value;
}
size_t trashsimulator__move_response__get_packed_size
                     (const Trashsimulator__MoveResponse *message)
{
  assert(message->base.descriptor == &trashsimulator__move_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trashsimulator__move_response__pack
                     (const Trashsimulator__MoveResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &trashsimulator__move_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trashsimulator__move_response__pack_to_buffer
                     (const Trashsimulator__MoveResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &trashsimulator__move_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Trashsimulator__MoveResponse *
       trashsimulator__move_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Trashsimulator__MoveResponse *)
     protobuf_c_message_unpack (&trashsimulator__move_response__descriptor,
                                allocator, len, data);
}
void   trashsimulator__move_response__free_unpacked
                     (Trashsimulator__MoveResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &trashsimulator__move_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor trashsimulator__join__field_descriptors[1] =
{
  {
    "join_code",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trashsimulator__Join, join_code),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trashsimulator__join__field_indices_by_name[] = {
  0,   /* field[0] = join_code */
};
static const ProtobufCIntRange trashsimulator__join__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trashsimulator__join__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trashsimulator.Join",
  "Join",
  "Trashsimulator__Join",
  "trashsimulator",
  sizeof(Trashsimulator__Join),
  1,
  trashsimulator__join__field_descriptors,
  trashsimulator__join__field_indices_by_name,
  1,  trashsimulator__join__number_ranges,
  (ProtobufCMessageInit) trashsimulator__join__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trashsimulator__join_response__field_descriptors[1] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trashsimulator__JoinResponse, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trashsimulator__join_response__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
};
static const ProtobufCIntRange trashsimulator__join_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor trashsimulator__join_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trashsimulator.JoinResponse",
  "JoinResponse",
  "Trashsimulator__JoinResponse",
  "trashsimulator",
  sizeof(Trashsimulator__JoinResponse),
  1,
  trashsimulator__join_response__field_descriptors,
  trashsimulator__join_response__field_indices_by_name,
  1,  trashsimulator__join_response__number_ranges,
  (ProtobufCMessageInit) trashsimulator__join_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trashsimulator__move_command__field_descriptors[2] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trashsimulator__MoveCommand, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "command",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trashsimulator__MoveCommand, command),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trashsimulator__move_command__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  1,   /* field[1] = command */
};
static const ProtobufCIntRange trashsimulator__move_command__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trashsimulator__move_command__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trashsimulator.MoveCommand",
  "MoveCommand",
  "Trashsimulator__MoveCommand",
  "trashsimulator",
  sizeof(Trashsimulator__MoveCommand),
  2,
  trashsimulator__move_command__field_descriptors,
  trashsimulator__move_command__field_indices_by_name,
  1,  trashsimulator__move_command__number_ranges,
  (ProtobufCMessageInit) trashsimulator__move_command__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor trashsimulator__move_response__field_descriptors[2] =
{
  {
    "client_id",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Trashsimulator__MoveResponse, client_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "status",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Trashsimulator__MoveResponse, status),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trashsimulator__move_response__field_indices_by_name[] = {
  0,   /* field[0] = client_id */
  1,   /* field[1] = status */
};
static const ProtobufCIntRange trashsimulator__move_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor trashsimulator__move_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "trashsimulator.MoveResponse",
  "MoveResponse",
  "Trashsimulator__MoveResponse",
  "trashsimulator",
  sizeof(Trashsimulator__MoveResponse),
  2,
  trashsimulator__move_response__field_descriptors,
  trashsimulator__move_response__field_indices_by_name,
  1,  trashsimulator__move_response__number_ranges,
  (ProtobufCMessageInit) trashsimulator__move_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
