# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x12\ttrashship\"I\n\x06Planet\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x11\n\tisrecycle\x18\x03 \x01(\x05\x12\x16\n\x0erecycled_count\x18\x04 \x01(\x05\"O\n\x0cPlanetUpdate\x12\x14\n\x0cplanet_index\x18\x01 \x01(\x05\x12\x11\n\tisrecycle\x18\x02 \x01(\x05\x12\x16\n\x0erecycled_count\x18\x03 \x01(\x05\"-\n\x05Trash\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0e\n\x06status\x18\x03 \x01(\x05\"7\n\x04Ship\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\n\n\x02ID\x18\x03 \x01(\x05\x12\r\n\x05\x63\x61rgo\x18\x04 \x01(\x05\"z\n\x13InitialSetupMessage\x12\"\n\x07planets\x18\x01 \x03(\x0b\x32\x11.trashship.Planet\x12\x1f\n\x05trash\x18\x02 \x03(\x0b\x32\x10.trashship.Trash\x12\x1e\n\x05ships\x18\x03 \x03(\x0b\x32\x0f.trashship.Ship\"z\n\rUpdateMessage\x12(\n\x07planets\x18\x01 \x03(\x0b\x32\x17.trashship.PlanetUpdate\x12\x1f\n\x05trash\x18\x02 \x03(\x0b\x32\x10.trashship.Trash\x12\x1e\n\x05ships\x18\x03 \x03(\x0b\x32\x0f.trashship.Ship\"1\n\rClientMessage\x12\x0f\n\x07ship_id\x18\x01 \x01(\r\x12\x0f\n\x07\x63ommand\x18\x02 \x01(\r\"g\n\rServerMessage\x12\x0f\n\x07ship_id\x18\x01 \x01(\r\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\x35\n\rinitial_setup\x18\x03 \x01(\x0b\x32\x1e.trashship.InitialSetupMessage')



_PLANET = DESCRIPTOR.message_types_by_name['Planet']
_PLANETUPDATE = DESCRIPTOR.message_types_by_name['PlanetUpdate']
_TRASH = DESCRIPTOR.message_types_by_name['Trash']
_SHIP = DESCRIPTOR.message_types_by_name['Ship']
_INITIALSETUPMESSAGE = DESCRIPTOR.message_types_by_name['InitialSetupMessage']
_UPDATEMESSAGE = DESCRIPTOR.message_types_by_name['UpdateMessage']
_CLIENTMESSAGE = DESCRIPTOR.message_types_by_name['ClientMessage']
_SERVERMESSAGE = DESCRIPTOR.message_types_by_name['ServerMessage']
Planet = _reflection.GeneratedProtocolMessageType('Planet', (_message.Message,), {
  'DESCRIPTOR' : _PLANET,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.Planet)
  })
_sym_db.RegisterMessage(Planet)

PlanetUpdate = _reflection.GeneratedProtocolMessageType('PlanetUpdate', (_message.Message,), {
  'DESCRIPTOR' : _PLANETUPDATE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.PlanetUpdate)
  })
_sym_db.RegisterMessage(PlanetUpdate)

Trash = _reflection.GeneratedProtocolMessageType('Trash', (_message.Message,), {
  'DESCRIPTOR' : _TRASH,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.Trash)
  })
_sym_db.RegisterMessage(Trash)

Ship = _reflection.GeneratedProtocolMessageType('Ship', (_message.Message,), {
  'DESCRIPTOR' : _SHIP,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.Ship)
  })
_sym_db.RegisterMessage(Ship)

InitialSetupMessage = _reflection.GeneratedProtocolMessageType('InitialSetupMessage', (_message.Message,), {
  'DESCRIPTOR' : _INITIALSETUPMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.InitialSetupMessage)
  })
_sym_db.RegisterMessage(InitialSetupMessage)

UpdateMessage = _reflection.GeneratedProtocolMessageType('UpdateMessage', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.UpdateMessage)
  })
_sym_db.RegisterMessage(UpdateMessage)

ClientMessage = _reflection.GeneratedProtocolMessageType('ClientMessage', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.ClientMessage)
  })
_sym_db.RegisterMessage(ClientMessage)

ServerMessage = _reflection.GeneratedProtocolMessageType('ServerMessage', (_message.Message,), {
  'DESCRIPTOR' : _SERVERMESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:trashship.ServerMessage)
  })
_sym_db.RegisterMessage(ServerMessage)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLANET._serialized_start=29
  _PLANET._serialized_end=102
  _PLANETUPDATE._serialized_start=104
  _PLANETUPDATE._serialized_end=183
  _TRASH._serialized_start=185
  _TRASH._serialized_end=230
  _SHIP._serialized_start=232
  _SHIP._serialized_end=287
  _INITIALSETUPMESSAGE._serialized_start=289
  _INITIALSETUPMESSAGE._serialized_end=411
  _UPDATEMESSAGE._serialized_start=413
  _UPDATEMESSAGE._serialized_end=535
  _CLIENTMESSAGE._serialized_start=537
  _CLIENTMESSAGE._serialized_end=586
  _SERVERMESSAGE._serialized_start=588
  _SERVERMESSAGE._serialized_end=691
# @@protoc_insertion_point(module_scope)
